//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class fermentable
    {
        public int id { get; set; }
        public string name { get; set; }
        public string ftype { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<float> yield { get; set; }
        public Nullable<float> color { get; set; }
        public Nullable<bool> add_after_boil { get; set; }
        public string origin { get; set; }
        public string supplier { get; set; }
        public string notes { get; set; }
        public Nullable<float> coarse_fine_diff { get; set; }
        public Nullable<float> moisture { get; set; }
        public Nullable<float> diastatic_power { get; set; }
        public Nullable<float> protein { get; set; }
        public Nullable<float> max_in_batch { get; set; }
        public Nullable<bool> recommend_mash { get; set; }
        public Nullable<bool> is_mashed { get; set; }
        public Nullable<float> ibu_gal_per_lb { get; set; }
        public Nullable<short> display_unit { get; set; }
        public Nullable<short> display_scale { get; set; }
        public Nullable<short> deleted { get; set; }
        public Nullable<short> display { get; set; }
        public string folder { get; set; }
    }
}
