//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class hop
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<float> alpha { get; set; }
        public Nullable<float> amount { get; set; }
        public string use { get; set; }
        public Nullable<float> time { get; set; }
        public string notes { get; set; }
        public string htype { get; set; }
        public string form { get; set; }
        public Nullable<float> beta { get; set; }
        public Nullable<float> hsi { get; set; }
        public string origin { get; set; }
        public string substitutes { get; set; }
        public Nullable<float> humulene { get; set; }
        public Nullable<float> caryophyllene { get; set; }
        public Nullable<float> cohumulone { get; set; }
        public Nullable<float> myrcene { get; set; }
        public Nullable<short> display_unit { get; set; }
        public Nullable<short> display_scale { get; set; }
        public Nullable<short> deleted { get; set; }
        public Nullable<short> display { get; set; }
        public string folder { get; set; }
    }
}
