//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class misc
    {
        public int id { get; set; }
        public string name { get; set; }
        public string mtype { get; set; }
        public string use { get; set; }
        public Nullable<float> time { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<bool> amount_is_weight { get; set; }
        public Nullable<bool> use_for { get; set; }
        public string notes { get; set; }
        public Nullable<short> display_unit { get; set; }
        public Nullable<short> display_scale { get; set; }
        public Nullable<short> deleted { get; set; }
        public Nullable<short> display { get; set; }
        public string folder { get; set; }
    }
}
