//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class style
    {
        public int id { get; set; }
        public string name { get; set; }
        public string s_type { get; set; }
        public string category { get; set; }
        public Nullable<short> category_number { get; set; }
        public string style_letter { get; set; }
        public string style_guide { get; set; }
        public Nullable<float> og_min { get; set; }
        public Nullable<float> og_max { get; set; }
        public Nullable<float> fg_min { get; set; }
        public Nullable<float> fg_max { get; set; }
        public Nullable<float> ibu_min { get; set; }
        public Nullable<float> ibu_max { get; set; }
        public Nullable<float> color_min { get; set; }
        public Nullable<float> color_max { get; set; }
        public Nullable<float> abv_min { get; set; }
        public Nullable<float> abv_max { get; set; }
        public Nullable<float> carb_min { get; set; }
        public Nullable<float> carb_max { get; set; }
        public string notes { get; set; }
        public string profile { get; set; }
        public string ingredients { get; set; }
        public string examples { get; set; }
        public Nullable<short> deleted { get; set; }
        public Nullable<short> display { get; set; }
        public string folder { get; set; }
    }
}
