//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class yeast
    {
        public int id { get; set; }
        public string name { get; set; }
        public string ytype { get; set; }
        public string form { get; set; }
        public Nullable<double> amount { get; set; }
        public string amount_is_weight { get; set; }
        public string laboratory { get; set; }
        public string product_id { get; set; }
        public Nullable<double> min_temperature { get; set; }
        public Nullable<double> max_temperature { get; set; }
        public string flocculation { get; set; }
        public Nullable<double> attenuation { get; set; }
        public string notes { get; set; }
        public string best_for { get; set; }
        public Nullable<double> times_cultured { get; set; }
        public Nullable<double> max_reuse { get; set; }
        public string add_to_secondary { get; set; }
        public Nullable<double> display_unit { get; set; }
        public Nullable<int> display_scale { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> display { get; set; }
        public string folder { get; set; }
    }
}
